###
GET http://127.0.0.1:8000/memo
###
GET http://127.0.0.1:8000/memo?userId=8h4osk
###
GET http://127.0.0.1:8000/search
###

DELETE  http://127.0.0.1:8000/memo/62ca531f06bdf9438cc15086

###

POST  http://127.0.0.1:8000/memo
Content-Type: application/json

{
  "userId":"8hsoaskalbfalk",
  "largeData":[
    {
      "type":"gakutika",
      "title": "学ちか",
       "smallData": [
            {
                "length": 210,
                "secret":false,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            },
            {
                "length": 400,
                "secret":false,
                "text": "東南アジアの経済について学んでいる私は、地域間の教育格差へ問題意識を向け、プロジェクトへの参加を決意しました。プロジェクトリーダーを努め、様々な業種に携わる人々を小中学校に招き、自身の職業について講演、ワークショップを行うキャリアセミナーを提案しました。「講師の募集」「現地の小中学校の承諾を得ること」が最大の困難でした。この2点について、まず、講師の募集についてはターゲットを絞り込み自ら声掛けをすることでターゲット大学の学生を巻き込み50人以上の協力を得られました。また、小中学校の承諾を得るために、自ら足を動かし全15校の承諾を得られました。半年間に渡ったプロジェクトは、7日間で1,000人以上の小中学生が参加し想定以上の人数が参加してくれました。地元じゃない土地ではありましたが、主体性を活かしプロジェクトを達成した経験は困難な状況をチームワークで乗り越えることができる学びができました。"
            }
            ]
    },
    {
      "type":"zikopr",
      "title": "自己PR",
       "smallData": [
            {
                "length": 210,
                "secret":false,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            }
            ]
    }
  ]
}

###

POST  http://127.0.0.1:8000/memo
Content-Type: application/json

{
  "userId":"8adkjbakdnl",
  "largeData":[
    {
      "type":"ziku",
      "title": "軸",
       "smallData": [
            {
                "length": 210,
                "secret":true,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            },
            {
                "length": 400,
                "secret":false,
                "text": "東南アジアの経済について学んでいる私は、地域間の教育格差へ問題意識を向け、プロジェクトへの参加を決意しました。プロジェクトリーダーを努め、様々な業種に携わる人々を小中学校に招き、自身の職業について講演、ワークショップを行うキャリアセミナーを提案しました。「講師の募集」「現地の小中学校の承諾を得ること」が最大の困難でした。この2点について、まず、講師の募集についてはターゲットを絞り込み自ら声掛けをすることでターゲット大学の学生を巻き込み50人以上の協力を得られました。また、小中学校の承諾を得るために、自ら足を動かし全15校の承諾を得られました。半年間に渡ったプロジェクトは、7日間で1,000人以上の小中学生が参加し想定以上の人数が参加してくれました。地元じゃない土地ではありましたが、主体性を活かしプロジェクトを達成した経験は困難な状況をチームワークで乗り越えることができる学びができました。"
            }
            ]
    },
    {
      "type":"zikopr",
      "title": "自己PR",
       "smallData": [
            {
                "length": 210,
                "secret":false,
                "text": "社会学のゼミで取り組んだ農村都市のPR活動のリーダーとしての仕事です。コロナ禍によりゼミ生との接点が少なくなりチームとしてやる気を無くしていました。そこで1週間に1度オンライン会議をおこない、PR活動の話だけではなく、個人の1週間の出来事を1分間で話す時間を設けました。結果以前よりもゼミ生同士の会話が増え、PR活動の取り組みもスムーズに進めることができました。"
            }
            ]
    }
  ]
}

